server:
  port: 9000
spring:  
  application:
    name: addition-service 
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-server-port: 8761
    service-url:
     defaultZone: http://127.0.0.1:8761/eureka/